---
- name: 'Import assert tasks'
  ansible.builtin.import_tasks: 'assert.yml'

- name: 'Include OS-specific variables'
  ansible.builtin.include_vars: '{{ distribution }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - 'default.yml'
  loop_control:
    loop_var: distribution

- name: 'Include OS-specific tasks for Domain Join'
  ansible.builtin.include_tasks: '{{ ansible_system }}/domain-join.yml'

- name: 'Include OS-specific tasks for Add Domain Administrators'
  ansible.builtin.include_tasks: '{{ ansible_system }}/add-domain-admins.yml'
