---
# handlers file for domain-join

- name: 'Restart SSSD'
  service:
    name: sssd
    state: restarted

- name: 'Reboot Windows'
  win_reboot:
  when: domain_join_result.reboot_required

- name: 'Wait for connection'
  wait_for_connection:
    timeout: 900