---
# handlers file for domain-join

- name: 'Linux | Restart SSSD'
  service:
    name: sssd
    state: restarted

- name: 'Windows | Reboot'
  win_reboot:
  when: domain_join_result.reboot_required

- name: 'Windows | Wait for connection'
  wait_for_connection:
    timeout: 900