---

- name: 'Linux | Configure sudo permissions'
  template:
    src: sudoers-domain-admins.j2
    dest: /etc/sudoers.d/domain-admins
    owner: root
    group: root
    mode: 0600
    validate: /usr/sbin/visudo -cf %s
