---

- name: Install packages
  package:
    name: '{{ domain_join__packages }}'
    state: present

- block:
  - name: Checking Active Directory domain join status for Linux
    shell: '/usr/sbin/realm --membership-software=adcli discover {{ domain_join__dns_domain_name }} | grep "configured: kerberos-member"'
    changed_when: false
  rescue:
    - name: Join Linux to an Active Directory domain
      shell: '/bin/echo {{ domain_join__password }} | /usr/sbin/realm --membership-software=adcli join {{ domain_join__dns_domain_name }} --user={{ domain_join__username }} --computer-ou={{ domain_join__ou_path }} --os-name={{ ansible_distribution }} --os-version={{ ansible_distribution_major_version }}'

- name: Configure sssd
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  notify: Restart SSSD

- name: Configure kerberos
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644