---

- name: 'Debian | Install required packages'
  apt:
    name: '{{ domain_join__packages }}'
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: 'RedHat | Install required packages'
  yum:
    name: '{{ domain_join__packages }}'
    state: present
  when: ansible_os_family == 'RedHat'

- block:
    - name: 'Linux | Checking Active Directory domain join status'
      shell: '/usr/sbin/realm --membership-software=adcli discover {{ domain_join__dns_domain_name }} | grep "configured: kerberos-member"'
      changed_when: false
  rescue:
    - name: 'Linux | Join to an Active Directory domain'
      shell: '/bin/echo {{ domain_join__password }} | /usr/sbin/realm --membership-software=adcli join {{ domain_join__dns_domain_name }} --user={{ domain_join__username }} --computer-ou={{ domain_join__ou_path }} --os-name={{ ansible_distribution }} --os-version={{ ansible_distribution_major_version }}'

- name: 'Linux | Configure SSSD'
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - Linux | Restart SSSD
    - Debian | Enable mkhomedir

- name: 'Linux | Configure Kerberos'
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
