---
- name: 'Windows | Add a users to local Administrators group'
  win_group_membership:
    name: Administrators
    members: '{{ admin }}@{{ domain_join_dns_domain_name }}'
    state: present
  loop: '{{ domain_join_admin_groups }}'
  loop_control:
    loop_var: admin
