---

- name: Join Windows to an Active Directory domain
  win_domain_membership:
    dns_domain_name: '{{ domain_join__dns_domain_name }}'
    domain_admin_user: '{{ domain_join__username }}@{{ domain_join__dns_domain_name }}'
    domain_admin_password: '{{ domain_join__password }}'
    domain_ou_path: '{{ domain_join__ou_path }}'
    state: domain
  register: domain_join_result

- name: Reboot Windows after Active Directory domain joining
  win_reboot:
  when: domain_join_result.reboot_required

- name: Wait for system to become reachable over WinRM
  wait_for_connection:
    timeout: 900