---

- name: 'Windows | Join to an Active Directory domain'
  win_domain_membership:
    dns_domain_name: '{{ domain_join__dns_domain_name }}'
    domain_admin_user: '{{ domain_join__username }}@{{ domain_join__dns_domain_name }}'
    domain_admin_password: '{{ domain_join__password }}'
    domain_ou_path: '{{ domain_join__ou_path }}'
    state: domain
  register: domain_join_result
  notify:
    - Windows | Reboot
    - Windows | Wait for connection